[core]
# On active les modules essentiels : fenêtres, animations et flou
plugins = autostart decoration blur animate expo vswitch

[decoration]
# LE STYLE MAC : Boutons à gauche (Fermer, Réduire, Agrandir)
layout = close | minimize maximize
font = Cantarell 11
# On arrondit les angles des fenêtres
border_radius = 12

[blur]
# L'effet "verre" derrière les fenêtres
method = kawase
iterations = 5
offset = 2

[autostart]
# On lancera le dock automatiquement ici plus tard
panel = wf-panel
dock = plank
