# --- IDENTITÉ BOOT ---
loader_logo="pamplemouche"

# --- CONFIGURATION GRAPHIQUE ---
vbe_max_resolution="1024x768"
autoboot_delay="2"

# --- PILOTES ET NOYAU ---
cpu_microcode_load="YES"
kern.vty=vt
