# --- IDENTITÉ DE L'OS (Pamplemouche Tech) ---
hostname="Pamplemouche-Core-Dev"

# --- RÉSEAU ---
ifconfig_DEFAULT="DHCP"

# --- SERVICES DE BASE ---
dbus_enable="YES"
moused_enable="YES"

# --- OPTIMISATION LÉGÈRETÉ (iPad 9) ---
sendmail_enable="NONE"
cron_enable="NO"
syslogd_enable="NO"

# --- ACCÈS DISTANT ---
sshd_enable="YES"
